#ifndef D015C350_E085_4625_95ED_5F4EC1033A0F
#define D015C350_E085_4625_95ED_5F4EC1033A0F

#include <Eigen/Core>
#include <Eigen/SVD>
#include <Eigen/LU>

/**
 * @brief (Doc Generated by ChatGPT) Computes the Moore-Penrose pseudo-inverse of a matrix using Singular Value
 * Decomposition (SVD)
 *
 * This implementation uses BDCSVD (Bi-Diagonal Singular Value Decomposition) from the Eigen library
 * to compute the pseudo-inverse of a matrix. The pseudo-inverse is calculated using the formula:
 * A⁺ = V * Σ⁺ * Uᴴ, where Σ⁺ contains reciprocals of singular values above the threshold.
 *
 * @tparam MatType Matrix type from Eigen library
 * @param InMat Input matrix to compute pseudo-inverse for
 * @param InEpsilon Threshold value for singular values (defaults to machine epsilon)
 *
 * @return Eigen::Matrix<typename MatType::Scalar, -1, -1> Pseudo-inverse of the input matrix
 *
 * @note The function uses dynamic-sized matrices internally but preserves compile-time maximum dimensions
 * @note Singular values below threshold (InEpsilon * max(rows, cols)) are treated as zero
 */
template<typename MatType>
Eigen::Matrix<typename MatType::Scalar, -1, -1> CalcSVD_MatInv(const MatType& InMat,
	double InEpsilon = std::numeric_limits<double>::epsilon())
{
	// Define working matrix type with dynamic size but using compile-time max dimensions
	using WorkingMatType = Eigen::Matrix<typename MatType::Scalar, Eigen::Dynamic, Eigen::Dynamic, 0,
		MatType::MaxRowsAtCompileTime, MatType::MaxColsAtCompileTime>;

	// Compute SVD decomposition with full U and V matrices
	Eigen::BDCSVD<WorkingMatType> svd(InMat, Eigen::ComputeFullU | Eigen::ComputeFullV);

	// Set threshold for singular values
	svd.setThreshold(InEpsilon * std::max(InMat.cols(), InMat.rows()));

	// Get effective rank
	Eigen::Index rank = svd.rank();

	// Define temporary matrix for computation
	Eigen::Matrix<typename MatType::Scalar, Eigen::Dynamic, MatType::RowsAtCompileTime, 0,
		Eigen::BDCSVD<WorkingMatType>::MaxDiagSizeAtCompileTime, MatType::MaxRowsAtCompileTime>
		tmp = svd.matrixU().leftCols(rank).adjoint();

	// Calculate inverse using singular values
	tmp = svd.singularValues().head(rank).asDiagonal().inverse() * tmp;

	// Compute final pseudo-inverse
	return svd.matrixV().leftCols(rank) * tmp;
}

template<typename Scalar = double, int ForceCount = 2>
class TFingerForceBalancer
{
	constexpr static bool ASSERT_RESULT_BALANCED = true;
	using GraspingMatrixType        = Eigen::Matrix<Scalar, 6, ForceCount * 3>; // 6 x 3N Matrix type  Fx Fy Fz Tx Ty Tz
	using GraspingMatrixInverseType = Eigen::Matrix<Scalar, ForceCount * 3, 6>;
	using NullSpaceIdentityType     = Eigen::Matrix<Scalar, ForceCount * 3, ForceCount * 3>;

	using GraspPointListType = Eigen::Matrix<Scalar, ForceCount, 3>; // N x 3 matrix type.
public:
	using ForceListType = Eigen::Matrix<Scalar, ForceCount * 3, 1>; // 3N x 1 vector type.

private:
	using Mat3x3 = Eigen::Matrix<Scalar, 3, 3>;
	using Vec3   = Eigen::Matrix<Scalar, 3, 1>;
	using Vec6   = Eigen::Matrix<Scalar, 6, 1>;

	Eigen::Matrix<Scalar, 3, 1> CoM; // Center of mass

public:
	GraspPointListType PointList;
	GraspingMatrixType GMat;
	GraspingMatrixInverseType GMatInv;
	NullSpaceIdentityType NullSpaceIdentity = NullSpaceIdentityType::Identity();

	Vec6 ExternalForce;

public:
	EIGEN_MAKE_ALIGNED_OPERATOR_NEW

	TFingerForceBalancer(const Vec3& InCoM)
	{
		for ( int i = 0; i < ForceCount; i++ )
		{
			GMat.template block<3, 3>(0, i * 3) = Mat3x3::Identity();
		}
	}

	TFingerForceBalancer(const Vec3& InCoM, const Vec6& InExternalForce)
		: CoM(InCoM), ExternalForce(InExternalForce) { }

	void SetExternalForce(const Vec6& InExternalForce) { ExternalForce = InExternalForce; }

	void MakeGMat(const GraspPointListType& InPointListMat, bool bInDebug = false)
	{
		PointList = InPointListMat;
		for ( int i = 0; i < ForceCount; i++ )
		{
			const Vec3& CurrentGraspPoint = InPointListMat.row(i);
			const Vec3& m                 = CurrentGraspPoint - this->CoM;
			// clang-format off
			GMat.template block<3, 3> (3, i * 3) <<  0    ,   -m (2),   m (1),
													 m (2),    0	,  -m (0),
													-m (1),    m (0),   0		;
			// clang-format on
		}
		const auto&& res                                = CalcSVD_MatInv(GMat);
		GMatInv.template block<ForceCount * 3, 6>(0, 0) = res.template block<ForceCount * 3, 6>(0, 0);
	}

	bool MakeForceBalanced(ForceListType& InOutInitForce)
	{
		// 计算【当前手指力与平衡力】之间的误差
		const Vec6&& BalancedForceError = GMat * InOutInitForce - ExternalForce;

		// 完成后，通过误差进行修正，从而得到平衡力。
		InOutInitForce += GMatInv * (-BalancedForceError);

		if constexpr ( ASSERT_RESULT_BALANCED )
		{
			const Vec6&& BalanceRes = (GMat * InOutInitForce - ExternalForce);

			if ( !BalanceRes.isZero(1e-6) )
			{
				return false;
			}
		}
		return true;
	}

	[[deprecated("Use MakeForceBalanced instead")]] ForceListType CalculateFingerForeceByK(const ForceListType& InK)
	{
		return GMatInv * ExternalForce + (NullSpaceIdentity - GMatInv * GMat) * InK;
	}
};

#endif /* D015C350_E085_4625_95ED_5F4EC1033A0F */
